### ISSUE TITLE
Tracking Provenance

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#81]
Add a table that associates entity IDs with their  mapping rule so that OMOP data can be tracked back to its source in CCDA.

- [x] decide between a table and extra columns
  - a tracing_dict has been added to the output_dict in data_driven_parse and is then output as a separate csv/table. 
- [ ] add IDs to the rules
  - We can't perfectly assume the element id is unique, though it is nearly. 
-  firm up file locations and IDs
   -  firm up entity IDs, out of scope here, but see #83. Filenames, as long as unique are fine.
-  record (ccda_file_id, rule_id, omop_entity_id, date_of_run, code_release) or somesuch.
   - too broad a scope for today. Limit to current release.
- [ ] test: does the code work? is it useful?

**Comment by chrisroederucdenver** [comment]
Duplicate of #82

**Comment by chrisroederucdenver** [comment]
This was closed as a way to limit the list of bugs and subsume this in the uber/super ticket.
Since it shows up as done in too many places in this way, It is being re-opened to accurately and clearly reflect its incomplete state.
